### ISSUE TITLE
change boot wait sec has no effect

### ISSUE THREAD

**Issue by microcai** [edk2-porting/edk2-rk35xx#4]
by defailt  this firmware will wait 10s to boot OS.
change it to any value, in setup menu, save, and reset, value ramaines 10 second.

**Comment by Googulator** [comment]
EmuVariableDxe is being used for variable storage, which is a dummy in-memory variable store. Therefore, changes to UEFI variables (including anything that can be changed in setup) are lost upon reboot.

To fix this, a proper SPI flash-based variable store will need to be enabled instead of EmuVariableDxe.

**Comment by strongtz** [comment]
should work with https://github.com/edk2-porting/edk2-rk35xx/commit/a93a211e8e12cb3a57639c275637f7b082d3ed41
